server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: attendance-service
          uri: ${attendance.service.url}
          predicates:
            - Path=/api/attendance/**
        - id: auth-service
          uri: ${auth.service.url}
          predicates:
            - Path=/api/auth/**

attendance:
  service:
    url: attendance-service:8081

auth:
  service:
    url: auth-service:8082

springdoc:
  enable-native-support: true
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui/index.html
    config-url: /v3/api-docs/swagger-config
    operationsSorter: alpha
    tagsSorter: alpha
    urls:
      - url: /v3/api-docs
        name: API Gateway Service
        primaryName: API Gateway Service
      - url: /attendance-service/v3/api-docs
        name: Attendance Service
        primaryName: Attendance Service
      - url: /auth-service/v3/api-docs
        name: Auth Service
        primaryName: Auth Service